.dockerignore, .travis.yml, Dockerfile, go.mod, go.sum, internal/api/router.go, main.go, vendor/github.com/go-chi/chi/.gitignore, vendor/github.com/go-chi/chi/.travis.yml, vendor/github.com/go-chi/chi/CHANGELOG.md, vendor/github.com/go-chi/chi/CONTRIBUTING.md, vendor/github.com/go-chi/chi/LICENSE, vendor/github.com/go-chi/chi/README.md, vendor/github.com/go-chi/chi/chain.go, vendor/github.com/go-chi/chi/chi.go, vendor/github.com/go-chi/chi/context.go, vendor/github.com/go-chi/chi/mux.go, vendor/github.com/go-chi/chi/tree.go, vendor/modules.txt
This route serves our frontend SPA. Steps for testing locally:
* `make build`
* `docker run -p 8080:80 $CONTAINER`
* open browser at `$(docker-machine ip):8080/dashboard`
VELO-1413
=> Add /dashboard route

config.go
=> Nil Pointer Fix

main.go
=> fix dd metric name

config.go, main.go
and use the configured service port rather than hard coding it.
=> Build AWS config from service config

.travis.yml
=> Put go linting and testing into one job

.travis.yml
=> Add codecov to .travis.yml

internal/api/integrations/k8s/k8s.go, internal/api/models/release.go
=> Load all available fields to populate /releases endpoint for UI demo

api/release.json, internal/api/models/release.go
The response now returns an array of Docker artifacts, to support helm
releases that contain more than one image.
VELO-1511
=> Update /releases endpoint response

web/src/App.css, web/src/components/ImageInfoDialog.js
VELO-1511
All images linked to a given release are now listed in the docker dialog
window on the UI
=> List all Images linked to a HelmRelease in Docker UI window

.travis.yml, operator/Makefile
=> Set up TravisCI for operator module

cmd/ship-it-syncd/main.go, deploy/ship-it/templates/syncd-deployment.yaml, deploy/ship-it/values.yaml, internal/syncd/config/config.go
Adds the missing chart values that are required
=> Update syncd deployment values in ship-it chart

internal/syncd/integrations/k8s/informer.go
=> Wrap Cache Start in Go Routine

operator/api/v1beta1/helmrelease_types.go, operator/controllers/helmrelease_controller.go
This should allow us to test the rollback logic.
=> VELO-1532: reconcile rollback scaffold

internal/syncd/integrations/github/downloader.go, internal/syncd/integrations/github/downloader_test.go
The helm 'chartutil.LoadFiles' func expects filenames to be relative to
the chart root. Otherwise it rejects the chart for lacking
required files in subdirectories like 'templates/'
=> fixup syncd chart downloader

deploy/ship-it/templates/api-deployment.yaml, deploy/ship-it/templates/clusterrolebinding.yaml, deploy/ship-it/templates/serviceaccount.yaml, deploy/ship-it/templates/syncd-deployment.yaml
The Informer requires a service account.
=> Give Syncd a Read Only Service Account

operator/controllers/helmrelease_controller.go
=> operator should re-use helm release name if it was deleted but not purged

internal/api/service/service_test.go, internal/image_test.go
cherry-picked from https://github.com/Wattpad/ship-it/pull/103
=> quell scopelint warnings

deploy/ship-it/Chart.yaml, deploy/ship-it/templates/api-deployment.yaml, deploy/ship-it/templates/syncd-deployment.yaml, deploy/ship-it/values.yaml
If set to true, uses the pod's host IP as the DOGSTATSD_HOST
=> Add useDogstatsdHostIP value

.travis.yml
=> Add helm chart publishing stage to ship-it’s CI

web/src/App.css, web/src/components/GridCell.js
=> Fix long service names wrap and break the grid

web/src/components/ExpandedCard.js, web/src/components/GridCell.js, web/src/components/StatusChip.js
=> Fix helm status not displaying

web/package-lock.json, web/package.json, web/src/components/ExpandedCard.js, web/src/index.css
I don't often see people here with a black on white terminal..
=> Use highlight.js to render helm status output

web/src/components/GridCell.js
=> Show time as well as date of last deploy

.gitignore, .travis.yml, README.md, operator/.gitignore, operator/Makefile
Addresses [PIE-2355](https://wattpad.atlassian.net/browse/PIE-2355)
We will stop paying for Codecov.io later this year so this PR removes all integrations with Codecov.io cleaning up code along the way.
=> Remove codecov.io integration
