.travis.yml

The code was already tested and linted in the PR build, so it's
redundant to run them again on the merge to master.

Don't re-run testing & linting on master builds

---

go.mod
go.sum
main.go

Add a service context to control the lifetime of the service's
subsystems. Includes termination signal handling and logging.

Add service lifetime context

---

Dockerfile
Makefile

The target runs the most recently built "ship-it "docker container with
AWS env credentials. It's intended to be used with aws-vault, ie.
`aws-vault exec wattpad -- make run`
In the future, this will likely be replaced by kubernetes deployment
manifests (helm chart), but it's useful for early development in the
meanwhile.

Add run makefile target

---

api/schema.json
go.mod
go.sum
internal/api/controller.go
internal/api/controller_test.go
internal/api/responses.go
internal/api/router.go
internal/models/deployment_detail.go
internal/models/release.go
internal/service/service.go
main.go

The /releases endpoint will return a list of deployment details for
each service registered with ship-it.
---
To test locally:
```
$ make build
$ aws-vault exec wattpad -- make run
```
Then make a request to `$(docker-machine ip):8080/releases`. The business logic is stubbed out, so this returns `{"code":500,"message":"not implemented"}`

VELO-1422: stub /releases endpoint

---

internal/api/router.go

The UI is now served from the root `/`, instead of `/dashboard`. The API
endpoints are served from the `/api` prefix.

Reorganize API routes

---

internal/helmrelease/helmrelease.go

These structs live in their own package so they can be easily shared,
since every component of ship-it will depend on it.
---
based off https://github.com/Wattpad/ship-it/blob/master/deploy/v1alpha1_helmrelease_crd.yaml

Add structs matching the HelmRelease custom resource

---

cmd/ship-it-api/main.go
internal/api/config/config.go
internal/api/integrations/k8s/k8s.go

This PR updates the API's k8s integration to use the generated HelmReleases informer instead of querying config maps.
---
This is still untested, but the code changes are pretty simple. I should test this out in minikube.

VELO-1457: lister integration

---

web/src/App.js

Skaffold can now be used to fully replicate production while testing the
web UI. As a result the address variable pointing to a mock local API is
no longer needed.

Remove Local API Address

---

.travis.yml
cmd/ship-it-ecrconsumer/Dockerfile
cmd/ship-it-syncd/Dockerfile
cmd/ship-it-syncd/main.go
internal/ecrconsumer/image_values.go
internal/ecrconsumer/image_values_test.go
internal/image.go
internal/image_test.go
internal/syncd/config/config.go
internal/syncd/multierror.go
internal/syncd/multierror_test.go
internal/syncd/syncd.go

This PR is in a bit of a weird state. It removes code we were using, like ecrconsumer in `cmd/ship-it-syncd/main.go` because that code needs to be updated to match the interfaces defined in `internal/syncd`. It adds code we're not using yet, like some of the config fields in `internal/syncd/config`, because we have blocked PRs depending on this code and I know the unused code will be used in those PRs.
The syncd package provides the image-registry/chart-repo/kube-cluster synchronization logic, but is abstracted to avoid being directly coupled to ECR+SQS/Github+SQS. We still need to think about how we'd choose between different implementations in a configurable way, but for now we can just hardcode our specific implementations. 
Also, I renamed it from `gitsync`, because if you look …

VELO-1475: syncd

---

internal/ecrconsumer/image_values.go
internal/ecrconsumer/image_values_test.go
operator/api/v1beta1/helmrelease_types.go
operator/api/v1beta1/helmrelease_types_test.go

Adding this method reduces code duplication and means that in the future
when we change the representation of the `Spec.Values` field, we'll only
need to update code in one place.

Add HelmValues method to HelmRelease type

---

operator/controllers/helmrelease_controller.go
operator/main.go

Create the HelmReleaseReconciler with a helm client so it can reconcile
HelmRelease events by modifying releases. Two method stubs are added to
handle reconciling deleted and updated HelmReleases.
VELO-1492

VELO-1492: Add high level reconcile logic

---

deploy/ship-it/templates/syncd-deployment.yaml
deploy/ship-it/values.yaml

VELO-1529
The `RELEASE_BRANCH` environment variable which points ship-it to the
branch in miranda it should commit to was missing from the chart.

Add Missing Release Branch Variable to Syncd

---

internal/syncd/integrations/ecr/listener.go
internal/syncd/integrations/ecr/listener_test.go

VELO-1529
The consumer returns an error when the image tag is not a valid commit
hash (ie. "latest"). The problem with this behaviour is that the SQS
consumer library believes the message has not been successfully
processed because the handler returned an error. As a result, the
invalid image is put back on the queue being processed over and over in an
endless loop. This PR has the handler return `nil` on these types of
images so they are removed from the queue. The invalid image tag error is still logged using the logger attached to the `ImageListener` type.

Fix Infinite Loop in ECR Queue Consumer

---

deploy/ship-it/values.yaml

VELO-1529
The AWS SDK does not accept the full URI as a valid queue name. As a result, I have changed the queue name environment variables to have just the name and nothing else. If there is a place where we need the full identifier, I will add logic to parse out the name instead.

Correct Queue Names in Ship-it Chart Values

---

internal/syncd/integrations/ecr/reconciler.go
internal/syncd/integrations/ecr/reconciler_test.go
internal/syncd/integrations/k8s/informer.go
internal/syncd/integrations/k8s/informer_test.go

VELO-1529
The indexer takes the full repository URI as a key. This PR calls the
`URI()` method on the input image and passes it to the `Lookup` method.

Fix Indexer Query

---

cmd/ship-it-syncd/main.go
deploy/ship-it/templates/syncd-deployment.yaml
deploy/ship-it/values.yaml
internal/syncd/config/config.go

VELO-1529
When testing Ship-it in scal-labs, I discovered that that new releases
could not be installed due to a timing out connection to Tiller. The
default Tiller host used by the helm client is not the same as ours. This
PR adds an environment variable for the Tiller host and adds the value
as an option when creating the helm client.

Fix Tiller Connection Issue

---

operator/chartdownloader/factory.go
operator/chartdownloader/factory_test.go
operator/chartdownloader/s3.go
operator/chartdownloader/s3_test.go
operator/main.go

The chartdownloader was picking a chart repository at application start
up, instead of using the values from the HelmRelease being reconciled.
The S3 downloader now correctly parses the bucket and object from the
chart URL.

Refactor chartdownloader & fixups

---

internal/syncd/integrations/github/downloader.go
internal/syncd/integrations/github/downloader_test.go

The downloader needs to preserve the full path of the file. Before it
would only save the filename, so a file like `foo/bar/file.yaml` would
be given a filename `file.yaml`. However when downloading a chart, which
contains nested directories like `chart/templates/*.yaml`, we need to
preserve the full file path in order to load the chart correctly.

Fixup syncd/github chart downloader

---

.travis.yml
cmd/ship-it-api/Dockerfile
cmd/ship-it-syncd/Dockerfile
operator/Dockerfile

doesn't look like there's any issues, builds are green

Bump golang version -> 1.13 in Travis & Dockerfiles

---

web/src/App.css
web/src/App.js
web/src/components/TileGrid.js
web/src/components/TopBar.js

This PR adds a search bar in the top bar of the web UI which allows people to filter the list of releases by name, owning squad or status. It's implemented by a simple string `includes` on each field to check if any field contains the query.
After searching, pressing the `x` that appears on the right of the search bar (or pressing escape) will clear the query, showing all the releases again.
Since this is my first PR to this repo, let me know if I'm missing anything. I checked the tests for the web UI, and it looks like there's only one really basic test. If we're going to start adding tests, let me know and I can add some to this PR.
VELO-1547

UI: Implement searching by release name, owning squad or status

---

deploy/ship-it/templates/syncd-deployment.yaml
deploy/ship-it/values.yaml

The reloader operator does a rolling deployment restart whenever one of
the secrets used by the deployment changes.
VELO-1542

Add stakater/reloader annotation to syncd deployment

---

cmd/ship-it-syncd/main.go
internal/syncd/integrations/ecr/reconciler.go
internal/syncd/integrations/ecr/reconciler_test.go

The reconciler doesn't use the logger, and ideally shouldn't ever need
to. Since the listener implementations have logging middleware, any
error returned normally by the reconciler will be logged after it
bubbles to the listener.

Remove unused ecr image reconciler logger

---

cmd/ship-it-api/Dockerfile

`npm install react-scripts` can take dozens of seconds to complete. The way it was written originally, any source code changes cause the layer that installs the scripts to be uncached. Re-organizing allows better re-use of cached layers and avoids re-downloading the same package during local dev.

Reduce ship-it-api build time by caching more

---

Makefile

The target depends on the user already having helm + helm-s3 plugin
installed and having added the 's3://charts.wattpadhq.com' repository to
their repo list.
https://github.com/hypnoglow/helm-s3
---
Adding a convenience target to publish the chart, so we can use it in the cluster-components chart in miranda.

Add Makefile target to publish ship-it chart

---

deploy/ship-it/Chart.yaml
deploy/ship-it/templates/external-secret.yaml
deploy/ship-it/values.yaml

We should eventually de-wattpad the chart's default values and configure it all in miranda. I commented something about this on VELO-1589 in jira. Then we could have a `prod-v3/values.yaml` without external secret, and a `prod-v4/values.yaml` using external secret.

Add ExternalSecret to ship-it chart

---

deploy/ship-it/Chart.yaml
deploy/ship-it/templates/operator-deployment.yaml
deploy/ship-it/values.yaml
operator/main.go

The operator is logging errors because it's not permitted to list resources at a cluster scope. I realized the `controllers.Namespace` option I had set previously controls which namespace tiller deploys into, not where the operator is watching for HelmRelease resources, so we need 2 different arguments.

ship-it-operator controller namespace scopes

---

.travis.yml
Makefile

Cuts build time from 12 minutes to roughly 7.5 minutes
- Build stage jobs run immediately after testing jobs so it re-uses cached packages
- Codecov to run in Test and Lint stage so we aren't running `go test` twice
- Use recommended and faster method for installing golangci-lint
VELO-1771

Speed up Travis build

---

internal/api/service/service.go

There was an error of `an empty namespace may not be set when a resource name is provided` when calling `curl -i localhost:31901/api/releases/my-service-name`. This sets the namespace for new services to be `default` instead of empty.

Fix GetRelease endpoint

---

internal/syncd/integrations/ecr/chart_editor.go
internal/syncd/integrations/ecr/chart_editor_test.go
internal/syncd/integrations/ecr/listener.go
internal/syncd/integrations/ecr/listener_test.go

If a new image is pushed but there are no registered releases that use
the image, the chart editor can exit early with a meaningful error
message. The error message can be logged so we can see what syncd is
doing even when there aren't many services registered.
---
I'm realizing there's a bit of ugliness in the way ship-it tracks the state of the registry chart right now. Most of the time the state of the registry chart release in the cluster is the source of truth, but this logic uses the state of the registry chart in github. 
Though those 2 states will eventually converge, it's possible that they differ at the moment ship-it observes them. I can't think of a concrete case where this actually causes problems, but I'm probably not being creative enough.

Handle "no affected registered releases" edge case in ECR reconciler

---

README.md

This question came up in the docs demo.

Add section to README about what causes a helm release to fail

---

internal/syncd/syncd_test.go

This file previously had 0% test coverage. This commit adds some simple
unit tests around the cancellation and error handling behaviour of the
syncd runner.

Improve test coverage for 'internal/syncd/syncd.go'
